### PR TITLE
Robin/20181205 fix webrtc stats

### PR DESCRIPTION
**Pull request by robin-raymond**

### CODE REVIEW

**Comment by robin-raymond** [comment]
@morosev please review - should this fix be brought to m71? If not then we need to reject it and I need to submit a PR just for the fix I did.

**Comment by robin-raymond** [comment]
@SergioOpenPeer We need @morosev to verify this fix first is appropriate so don't merge just yet to releases/m71 because it's picking up some other fixes too

**Review by morosev — CHANGES_REQUESTED** [review]
I'm fine with included changes for audio device, but they must follow the changes in webrtc, as well: https://github.com/webrtc-uwp/webrtc/commit/c4e4e32ac2cd13a659890bb9daf484ed9f995cf6
On the other hand, moving to external audio device won't require applying changes in webrtc. Maybe we could postpone merge of audio device flags to m71 until external audio device is added.

**Comment by robin-raymond** [comment]
@morosev I will create a new PR with just the change required and not pull in these changes since they seem to not be good for m71 using external devices.

**Pull request closed without merging**
