### PR TITLE
Prevent deadlock in GetMediaCapture()

### PR DESCRIPTION
**Pull request by jehumb-havok**
Ensure that MediaCapture finished initializing before returning the new
instance when running (pseudo-)synchronously, like in the purely
asynchronous case. Otherwise the returned instance is not initialized,
and some calls to methods and properties will fail.

### CODE REVIEW

**Comment by jehumb-havok** [comment]
Issue is legit, fix is wrong; this is deadlocking the UI thread. I will get a better one, sorry.

**Comment by morosev** [comment]
I applied the same fix here: https://github.com/webrtc-uwp/webrtc-apis/commit/92b366fcddd56ebfe74581033931f94baaa84213
But noticed as well that in some cases UI thread just shouldn't be used there. The deadlock occurs when user is asked to give permission for access to camera device (because the UI component is used here). Otherwise the deadlock won't occur. There is a current workaround to call InitAsync() method on capture device on application start from not blocked UI thread. In that case the window for camera permission is shown on application start. Anyway, blocking UI thread on InitAsync() call should be strongly forbidden.

**Comment by jehumb-havok** [comment]
Actually `GetMediaCapture()` is synchronous, so cannot be called on the UI thread:
- `MediaCapture.InitializeAsync()` needs to be called from the UI thread, [as per the docs](https://docs.microsoft.com/en-us/uwp/api/windows.media.capture.mediacapture.initializeasync).
- It needs the UI thread to be available for pumping the UI message loop, in case of a UI dialog asking for permission.
- `GetMediaCapture()` needs to wait for `InitializeAsync()` to complete, because the `MediaCapture` object will be used by the caller, and needs to be fully initialized.

Because of that, `GetMediaCapture()` will block the UI thread and induce a deadlock if called from that thread. So the correct "fix" is to throw an exception E_WRONGTHREAD in the `if (queue->isCurrentThread())` case, and fix in the caller if this is hit.

**Comment by jehumb-havok** [comment]
I rewrote most of the `GetMediaCapture()` to simplify it and add comments. It now throws an exception if called from the main UI thread. I am not sure what the implication is for its callers.

**Review by morosev — APPROVED** [review]
All good. That is the proper fix for calling on UI thread condition.

**Pull request merged**
